apiVersion: v1
kind: Service
metadata:
  name: {{ include "openssh-server.fullname" . }}
  labels:
    {{- include "openssh-server.labels" . | nindent 4 }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: ssh
      {{- if and (.Values.service.nodePort) (eq .Values.service.type "NodePort") }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
      {{- if .Values.service.loadBalancerIP }}
      loadBalancerIP: {{ .Values.service.loadBalancerIP }}
      {{- end }}
  selector:
    {{- include "openssh-server.selectorLabels" . | nindent 4 }}
