apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "openssh-server.fullname" . }}-custom-init
data:
  10-enable_tunnels: |-
    #!/usr/bin/with-contenv bash

    echo Enabling ProxyJump tunnel
    sed -i 's@#PermitTunnel no@PermitTunnel yes@' /etc/ssh/sshd_config
    sed -i 's@AllowTcpForwarding no@AllowTcpForwarding yes@' /etc/ssh/sshd_config
